# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BgJNBDCwOslHhKHb4n4PTrkChjIHWnVn
"""

import pandas as pd
import numpy as np

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

data = pd.read_csv("lung_cancer_dataset(1).csv")
print(data.head())

X = data.drop(columns=['survived'], errors='ignore')
X = pd.get_dummies(X, drop_first=True)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# convert back to DataFrame for readability
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

import matplotlib.pyplot as plt

wcss = []
K = range(1, 11)

for k in K:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    wcss.append(km.inertia_)

plt.figure()
plt.plot(K, wcss, marker='o')
plt.xlabel("Number of Clusters (k)")
plt.ylabel("WCSS")
plt.title("Elbow Method for Optimal k")
plt.show()

k = 2

kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X_scaled)

data['Cluster'] = clusters

sil_score = silhouette_score(X_scaled, clusters)
print("Silhouette Score:", sil_score)
print(data['Cluster'].value_counts())
print("Inertia (WCSS):", kmeans.inertia_)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure()
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=clusters)
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.title("K-Means Clustering (PCA Visualization)")
plt.show()

centroids_pca = pca.transform(kmeans.cluster_centers_)

plt.figure()
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=clusters)
plt.scatter(
    centroids_pca[:, 0],
    centroids_pca[:, 1],
    marker='X',
    s=200
)
plt.title("Cluster Centroids (PCA Space)")
plt.show()

new_patient = {
    'Age': 65,
    'Smoking': 1,
    'Yellow_Fingers': 0,
    'Anxiety': 1,
    'Peer_Pressure': 1,
    'Chronic_Disease': 0
}

new_patient_df = pd.DataFrame([new_patient])
new_patient_df = pd.get_dummies(new_patient_df)

new_patient_df = new_patient_df.reindex(columns=X.columns, fill_value=0)

new_patient_scaled = scaler.transform(new_patient_df)

prediction = kmeans.predict(new_patient_scaled)
print("Predicted Cluster:", prediction[0])

plt.figure()

plt.scatter(X_pca[:, 0], X_pca[:, 1], c=clusters)

# Plot cluster centroids
plt.scatter(
    centroids_pca[:, 0],
    centroids_pca[:, 1],
    marker='X',
    s=200
)

# Transform the new patient's scaled data into the PCA space
new_patient_pca = pca.transform(new_patient_scaled)

# Plot new patient
plt.scatter(
    new_patient_pca[:, 0],
    new_patient_pca[:, 1],
    marker='*',
    s=300,
    color='red',
    label='New Patient'
)

plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.title("K-Means Clustering with New Patient")
plt.legend()
plt.show()